const peptideData = [
  {
    id: "bpc-157",
    name: "BPC-157",
    category: "peptide",
    subcategory: "Healing & Recovery",
    fullName: "Body Protection Compound 157",
    description:
      "BPC-157 is a synthetic peptide derived from a protein found in human gastric juice. It is renowned for its remarkable healing and regenerative properties.",
    benefits: [
      "Accelerates wound and tissue healing",
      "Reduces inflammation",
      "Protects and heals the gut lining",
      "Supports tendon and ligament repair",
      "May improve joint health",
      "Neuroprotective effects",
      "May support angiogenesis (new blood vessel formation)",
    ],
    dosage: "250–500 mcg per day, administered subcutaneously or intramuscularly",
    halfLife: "~4 hours",
    sideEffects: ["Generally well tolerated", "Mild nausea reported in some users", "Injection site irritation"],
    researchStatus: "Preclinical (animal studies); human trials limited",
    tags: ["healing", "gut", "tendon", "inflammation", "recovery"],
  },
  {
    id: "tb-500",
    name: "TB-500",
    category: "peptide",
    subcategory: "Healing & Recovery",
    fullName: "Thymosin Beta-4 Fragment",
    description:
      "TB-500 is a synthetic version of a naturally occurring peptide fragment of Thymosin Beta-4. It promotes healing, reduces inflammation, and enhances flexibility.",
    benefits: [
      "Promotes muscle and tissue repair",
      "Reduces inflammation",
      "Improves flexibility and range of motion",
      "Supports cardiovascular healing",
      "Accelerates wound healing",
      "May promote hair growth",
    ],
    dosage: "2–2.5 mg twice weekly for the first 4–6 weeks, then a maintenance dose of 2–2.5 mg per month",
    halfLife: "~Unknown; long-acting",
    sideEffects: ["Mild head rush or nausea", "Fatigue", "Injection site pain"],
    researchStatus: "Preclinical; some human clinical trials underway",
    tags: ["healing", "muscle", "inflammation", "flexibility", "recovery"],
  },
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    category: "peptide",
    subcategory: "Anti-Aging & Skin",
    fullName: "Copper Peptide GHK-Cu",
    description:
      "GHK-Cu is a naturally occurring copper complex with a tripeptide sequence. It has powerful anti-aging, wound healing, and anti-inflammatory properties.",
    benefits: [
      "Stimulates collagen production",
      "Improves skin firmness and elasticity",
      "Reduces fine lines and wrinkles",
      "Accelerates wound healing",
      "Antioxidant properties",
      "May promote hair follicle growth",
      "Anti-inflammatory effects",
    ],
    dosage: "Topical: 0.1–1% in skincare formulations; Injectable: 1–2 mg per day",
    halfLife: "Short (hours)",
    sideEffects: ["Topical: very well tolerated", "Rare skin irritation", "Excessive copper intake risk if overused"],
    researchStatus: "Established in skin care; ongoing research for systemic use",
    tags: ["anti-aging", "skin", "collagen", "hair", "wound healing"],
  },
  {
    id: "sermorelin",
    name: "Sermorelin",
    category: "peptide",
    subcategory: "Growth Hormone",
    fullName: "Sermorelin Acetate (GHRH 1-29)",
    description:
      "Sermorelin is a synthetic analogue of the first 29 amino acids of endogenous growth hormone-releasing hormone (GHRH). It stimulates the pituitary gland to produce and secrete growth hormone.",
    benefits: [
      "Increases natural growth hormone production",
      "Improves body composition (increases lean mass, reduces fat)",
      "Enhanced recovery and sleep quality",
      "Improved energy levels",
      "Anti-aging effects",
      "Bone density improvements",
    ],
    dosage: "200–500 mcg subcutaneously before bed",
    halfLife: "~11–12 minutes",
    sideEffects: [
      "Injection site redness or pain",
      "Flushing",
      "Headache",
      "Dizziness",
      "Hyperactivity (rare)",
    ],
    researchStatus: "FDA-approved (was previously approved for pediatric GHD); widely used off-label",
    tags: ["growth hormone", "anti-aging", "muscle", "fat loss", "sleep"],
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    category: "peptide",
    subcategory: "Growth Hormone",
    fullName: "Ipamorelin",
    description:
      "Ipamorelin is a selective growth hormone secretagogue and ghrelin mimetic. It is one of the cleanest GH peptides available, stimulating GH release with minimal side effects.",
    benefits: [
      "Stimulates growth hormone release",
      "Increases lean muscle mass",
      "Reduces body fat",
      "Improves sleep quality",
      "Anti-aging properties",
      "Minimal cortisol or prolactin elevation",
    ],
    dosage: "200–300 mcg, 1–3 times per day subcutaneously",
    halfLife: "~2 hours",
    sideEffects: [
      "Headache",
      "Flushing",
      "Mild water retention",
      "Injection site discomfort",
    ],
    researchStatus: "Preclinical and early clinical trials; widely used off-label",
    tags: ["growth hormone", "muscle", "fat loss", "sleep", "anti-aging"],
  },
  {
    id: "cjc-1295",
    name: "CJC-1295",
    category: "peptide",
    subcategory: "Growth Hormone",
    fullName: "CJC-1295 (with or without DAC)",
    description:
      "CJC-1295 is a synthetic analogue of GHRH with an extended half-life. It stimulates growth hormone and IGF-1 secretion, with effects lasting several days.",
    benefits: [
      "Sustained elevation of growth hormone levels",
      "Increased IGF-1 production",
      "Improved muscle mass and fat metabolism",
      "Enhanced recovery",
      "Improved sleep quality",
    ],
    dosage: "CJC-1295 DAC: 1–2 mg weekly; CJC-1295 no-DAC: 100–200 mcg per dose",
    halfLife: "CJC-1295 DAC: 6–8 days; no-DAC: ~30 minutes",
    sideEffects: [
      "Water retention",
      "Fatigue",
      "Tingling sensation",
      "Headache",
      "Injection site reactions",
    ],
    researchStatus: "Clinical trials conducted; widely used off-label",
    tags: ["growth hormone", "IGF-1", "muscle", "fat loss", "recovery"],
  },
  {
    id: "pt-141",
    name: "PT-141",
    category: "peptide",
    subcategory: "Sexual Health",
    fullName: "Bremelanotide (PT-141)",
    description:
      "PT-141 is a synthetic peptide derived from Melanotan II. Unlike medications that act on the vascular system, PT-141 acts directly on the nervous system to increase sexual desire.",
    benefits: [
      "Increases sexual desire in men and women",
      "May help with erectile dysfunction",
      "Acts through central nervous system (not vasodilatory)",
      "Effective for hypoactive sexual desire disorder",
    ],
    dosage: "1–2 mg subcutaneously, 45–60 minutes before sexual activity",
    halfLife: "~2 hours",
    sideEffects: [
      "Nausea (most common)",
      "Flushing",
      "Headache",
      "Transient increase in blood pressure",
      "Hyperpigmentation with repeated use",
    ],
    researchStatus: "FDA-approved (Vyleesi) for HSDD in premenopausal women",
    tags: ["sexual health", "libido", "erectile dysfunction"],
  },
  {
    id: "selank",
    name: "Selank",
    category: "peptide",
    subcategory: "Nootropic & Mental Health",
    fullName: "Selank (TP-7)",
    description:
      "Selank is a synthetic analogue of the human tetrapeptide tuftsin. It has anxiolytic and nootropic properties and is used in Russia as a registered treatment for anxiety.",
    benefits: [
      "Reduces anxiety without sedation",
      "Improves memory and learning",
      "Enhances focus and mental clarity",
      "Antidepressant-like effects",
      "Immune modulation",
      "No addiction or withdrawal potential",
    ],
    dosage: "250–500 mcg intranasally or subcutaneously, 1–2 times per day",
    halfLife: "~2 minutes (but effects last hours)",
    sideEffects: ["Generally very well tolerated", "Mild fatigue reported", "Rare: nasal irritation"],
    researchStatus: "Approved medication in Russia; not approved in US/EU",
    tags: ["nootropic", "anxiety", "memory", "focus", "mood"],
  },
  {
    id: "semax",
    name: "Semax",
    category: "peptide",
    subcategory: "Nootropic & Mental Health",
    fullName: "Semax (ACTH 4-7 Pro8-Gly9-Pro10)",
    description:
      "Semax is a synthetic analogue of the ACTH fragment. It has potent nootropic, neuroprotective, and neurogenic properties.",
    benefits: [
      "Cognitive enhancement",
      "Neuroprotection",
      "May improve BDNF levels",
      "Improves attention and memory",
      "Anti-inflammatory in the nervous system",
      "Used in stroke recovery",
    ],
    dosage: "200–900 mcg intranasally per day",
    halfLife: "Minutes (but CNS effects persist hours)",
    sideEffects: ["Nasal irritation", "Mild headache", "Increased anxiety at high doses (rare)"],
    researchStatus: "Approved in Russia; investigational elsewhere",
    tags: ["nootropic", "neuroprotection", "memory", "BDNF", "cognitive"],
  },
  {
    id: "epithalon",
    name: "Epithalon",
    category: "peptide",
    subcategory: "Anti-Aging & Longevity",
    fullName: "Epithalamin / Epitalon (Ala-Glu-Asp-Gly)",
    description:
      "Epithalon is a synthetic tetrapeptide that acts as a telomerase activator. It is one of the most studied anti-aging peptides, originally developed in Russia.",
    benefits: [
      "Activates telomerase and extends telomere length",
      "Anti-aging and longevity effects",
      "Improves sleep quality (melatonin regulation)",
      "Antioxidant properties",
      "May reduce cancer risk",
      "Regulates neuroendocrine function",
    ],
    dosage: "5–10 mg per day for 10–20 days, repeated 1–2 times per year",
    halfLife: "Short",
    sideEffects: ["Very well tolerated in studies", "Rare injection site reactions"],
    researchStatus: "Extensive animal and some human studies; not approved as drug in West",
    tags: ["anti-aging", "telomere", "longevity", "sleep", "antioxidant"],
  },
  {
    id: "humanin",
    name: "Humanin",
    category: "peptide",
    subcategory: "Anti-Aging & Longevity",
    fullName: "Humanin (HN)",
    description:
      "Humanin is a small peptide encoded in the mitochondrial genome. It has cytoprotective, neuroprotective, and metabolic effects and is associated with longevity.",
    benefits: [
      "Neuroprotection (especially against Alzheimer's-related cell death)",
      "Improved insulin sensitivity",
      "Anti-apoptotic effects",
      "Cardiovascular protective properties",
      "Associated with longevity in centenarians",
    ],
    dosage: "Research dosages vary widely; not widely standardized for human use",
    halfLife: "Short",
    sideEffects: ["Limited human data available"],
    researchStatus: "Active preclinical and early clinical research",
    tags: ["longevity", "neuroprotection", "insulin", "mitochondria", "anti-aging"],
  },
  {
    id: "mots-c",
    name: "MOTS-c",
    category: "peptide",
    subcategory: "Metabolic & Performance",
    fullName: "Mitochondrial Open Reading Frame of the 12S rRNA-c",
    description:
      "MOTS-c is a mitochondria-derived peptide that regulates metabolic homeostasis, improves insulin sensitivity, and has anti-aging properties.",
    benefits: [
      "Increases insulin sensitivity",
      "Promotes fat oxidation",
      "Anti-obesity effects",
      "May enhance exercise performance",
      "Anti-aging and longevity effects",
      "Anti-inflammatory",
    ],
    dosage: "5–10 mg subcutaneously, 3–5 times per week",
    halfLife: "Short",
    sideEffects: ["Emerging data; generally well tolerated in studies"],
    researchStatus: "Preclinical and early human research phase",
    tags: ["metabolic", "insulin", "fat loss", "longevity", "mitochondria"],
  },
  {
    id: "ss-31",
    name: "SS-31",
    category: "peptide",
    subcategory: "Anti-Aging & Longevity",
    fullName: "Elamipretide (SS-31 / MTP-131)",
    description:
      "SS-31 is a mitochondria-targeted peptide that improves mitochondrial function and bioenergetics. It has cardioprotective and neuroprotective properties.",
    benefits: [
      "Improves mitochondrial function and efficiency",
      "Cardioprotective effects",
      "Reduces oxidative stress",
      "May improve age-related muscle weakness",
      "Neuroprotective properties",
    ],
    dosage: "0.05–0.25 mg/kg subcutaneously; clinical trials ongoing",
    halfLife: "~2–3 hours",
    sideEffects: ["Injection site reactions", "Nausea in some clinical trial participants"],
    researchStatus: "Phase II/III clinical trials ongoing",
    tags: ["mitochondria", "cardio", "anti-aging", "oxidative stress", "muscle"],
  },
  {
    id: "kisspeptin",
    name: "Kisspeptin",
    category: "peptide",
    subcategory: "Hormonal & Reproductive",
    fullName: "Kisspeptin-10 / Kisspeptin-54",
    description:
      "Kisspeptin is a neuropeptide that plays a crucial role in regulating the reproductive axis by stimulating GnRH release from the hypothalamus.",
    benefits: [
      "Stimulates LH and FSH release",
      "May help with hypogonadism",
      "Potential fertility treatment",
      "Regulates puberty onset",
    ],
    dosage: "Clinical doses range from 1–10 nmol/kg IV; research stage",
    halfLife: "~30 minutes (Kisspeptin-10)",
    sideEffects: ["Nausea", "Flushing", "Mild cardiovascular effects"],
    researchStatus: "Phase II clinical trials for reproductive disorders",
    tags: ["hormonal", "fertility", "LH", "FSH", "testosterone"],
  },
  {
    id: "aod-9604",
    name: "AOD-9604",
    category: "peptide",
    subcategory: "Metabolic & Performance",
    fullName: "Anti-Obesity Drug 9604",
    description:
      "AOD-9604 is a modified fragment of human growth hormone (hGH) that stimulates lipolysis and inhibits lipogenesis, without affecting growth or insulin levels.",
    benefits: [
      "Promotes fat burning (lipolysis)",
      "Inhibits fat formation (lipogenesis)",
      "No effect on blood sugar or growth",
      "May support cartilage repair",
    ],
    dosage: "300 mcg subcutaneously per day",
    halfLife: "~Unknown; relatively short",
    sideEffects: ["Generally well tolerated", "Mild redness at injection site"],
    researchStatus: "FDA GRAS designation; Phase IIb clinical trials conducted",
    tags: ["fat loss", "lipolysis", "metabolic", "weight loss"],
  },
  {
    id: "thymosin-alpha-1",
    name: "Thymosin Alpha-1",
    category: "peptide",
    subcategory: "Immune Support",
    fullName: "Thymalfasin (Tα1)",
    description:
      "Thymosin Alpha-1 is a naturally occurring thymic peptide that modulates the immune system. It enhances T-cell function and has antiviral and antitumor properties.",
    benefits: [
      "Enhances immune response",
      "Antiviral activity",
      "Antifungal properties",
      "Supports cancer treatment (as adjunct)",
      "Used in chronic hepatitis treatment",
      "Post-COVID immune support",
    ],
    dosage: "1.6 mg subcutaneously twice weekly (standard therapeutic dose)",
    halfLife: "~2 hours",
    sideEffects: ["Injection site reactions", "Mild flu-like symptoms initially", "Generally very safe"],
    researchStatus: "Approved in many countries for hepatitis B/C and cancer immune support",
    tags: ["immune", "antiviral", "T-cell", "cancer", "hepatitis"],
  },
  {
    id: "ll-37",
    name: "LL-37",
    category: "peptide",
    subcategory: "Immune Support",
    fullName: "LL-37 (Cathelicidin)",
    description:
      "LL-37 is an endogenous antimicrobial peptide and the only known human cathelicidin. It has broad-spectrum antimicrobial, anti-inflammatory, and wound-healing properties.",
    benefits: [
      "Broad-spectrum antimicrobial activity",
      "Promotes wound healing",
      "Anti-inflammatory effects",
      "Immune modulation",
      "May have anti-biofilm properties",
    ],
    dosage: "Typically 100–200 mcg per day or applied topically; research stage",
    halfLife: "Short",
    sideEffects: ["Can be pro-inflammatory at high concentrations", "Limited human data"],
    researchStatus: "Research phase; some topical formulations available",
    tags: ["immune", "antimicrobial", "wound healing", "inflammation"],
  },
];

const supplementData = [
  {
    id: "creatine",
    name: "Creatine Monohydrate",
    category: "supplement",
    subcategory: "Performance & Strength",
    description:
      "Creatine monohydrate is one of the most researched and effective sports supplements. It works by increasing phosphocreatine stores in muscles, enabling faster ATP regeneration.",
    benefits: [
      "Increases strength and power output",
      "Improves high-intensity exercise performance",
      "Increases muscle mass over time",
      "Improves brain performance and cognition",
      "May have neuroprotective properties",
      "Reduces fatigue",
    ],
    dosage: "3–5 g per day (no loading required); optional loading: 20 g/day for 5–7 days",
    timing: "Anytime; post-workout with carbs may slightly improve uptake",
    sideEffects: [
      "Water retention (intramuscular)",
      "Mild GI discomfort if taken in large single doses",
      "Slight weight gain (water-related initially)",
    ],
    evidence: "Extremely well-researched; Grade A evidence",
    tags: ["strength", "muscle", "performance", "brain", "ATP"],
  },
  {
    id: "whey-protein",
    name: "Whey Protein",
    category: "supplement",
    subcategory: "Protein & Amino Acids",
    description:
      "Whey protein is derived from milk during cheese production. It is a complete protein containing all essential amino acids and is rapidly absorbed, making it ideal post-workout.",
    benefits: [
      "Supports muscle protein synthesis",
      "Promotes muscle growth and repair",
      "Helps reach daily protein targets",
      "High in BCAAs, especially leucine",
      "May reduce hunger and support weight management",
    ],
    dosage: "20–40 g per serving; total daily intake based on protein needs (1.6–2.2 g/kg body weight)",
    timing: "Post-workout ideal; can be used anytime to meet protein goals",
    sideEffects: [
      "Digestive discomfort in lactose intolerant individuals",
      "Bloating (try whey isolate if issues occur)",
    ],
    evidence: "Grade A evidence for muscle protein synthesis",
    tags: ["protein", "muscle", "recovery", "amino acids", "leucine"],
  },
  {
    id: "bcaa",
    name: "BCAAs",
    category: "supplement",
    subcategory: "Protein & Amino Acids",
    fullName: "Branched-Chain Amino Acids (Leucine, Isoleucine, Valine)",
    description:
      "BCAAs are three essential amino acids—leucine, isoleucine, and valine—that are metabolized directly in muscle tissue. They play a key role in muscle protein synthesis and energy production.",
    benefits: [
      "Stimulates muscle protein synthesis (especially leucine)",
      "Reduces muscle soreness (DOMS)",
      "May reduce exercise fatigue",
      "Prevents muscle breakdown (anti-catabolic)",
      "Useful when training fasted",
    ],
    dosage: "5–10 g before or during workout",
    timing: "Pre-workout, intra-workout, or between meals",
    sideEffects: ["Generally safe", "Excessive intake may impair serotonin signaling", "Not necessary if protein intake is sufficient"],
    evidence: "Moderate evidence; most benefit seen in caloric deficit or low protein intake",
    tags: ["amino acids", "muscle", "recovery", "leucine", "fasted training"],
  },
  {
    id: "magnesium",
    name: "Magnesium",
    category: "supplement",
    subcategory: "Minerals & Electrolytes",
    description:
      "Magnesium is an essential mineral involved in over 300 enzymatic reactions in the body. It plays a critical role in energy production, protein synthesis, muscle function, and sleep.",
    benefits: [
      "Improves sleep quality",
      "Supports muscle relaxation and recovery",
      "Reduces anxiety and stress",
      "Supports bone health",
      "Regulates blood pressure",
      "Improves insulin sensitivity",
      "May reduce headaches and migraines",
    ],
    dosage: "200–400 mg elemental magnesium per day; Glycinate or Threonate recommended for better absorption",
    timing: "Before bed for sleep and relaxation benefits",
    sideEffects: [
      "Loose stools at high doses (especially magnesium oxide)",
      "Choose glycinate or threonate to minimize GI effects",
    ],
    evidence: "Strong evidence for deficiency correction; good evidence for sleep and anxiety",
    tags: ["sleep", "muscle", "anxiety", "bone", "insulin", "minerals"],
  },
  {
    id: "zinc",
    name: "Zinc",
    category: "supplement",
    subcategory: "Minerals & Electrolytes",
    description:
      "Zinc is an essential trace mineral with roles in immune function, protein synthesis, wound healing, testosterone production, and over 300 enzymatic processes.",
    benefits: [
      "Supports immune function",
      "May boost testosterone levels (especially if deficient)",
      "Promotes wound healing",
      "Antioxidant properties",
      "Supports thyroid function",
      "Important for male reproductive health",
    ],
    dosage: "15–30 mg per day of elemental zinc; take with food to reduce nausea",
    timing: "With meals",
    sideEffects: [
      "Nausea if taken on empty stomach",
      "Copper depletion with long-term high doses",
      "Consider zinc picolinate or bisglycinate for better absorption",
    ],
    evidence: "Strong evidence for immune support and deficiency correction",
    tags: ["immune", "testosterone", "wound healing", "minerals", "antioxidant"],
  },
  {
    id: "vitamin-d3",
    name: "Vitamin D3",
    category: "supplement",
    subcategory: "Vitamins",
    fullName: "Cholecalciferol (Vitamin D3)",
    description:
      "Vitamin D3 is a fat-soluble vitamin produced in skin exposed to sunlight. It acts as a hormone precursor and is involved in calcium regulation, immune function, mood, and numerous other processes.",
    benefits: [
      "Supports bone health and calcium absorption",
      "Strengthens immune system",
      "May improve mood and reduce depression",
      "Supports muscle function",
      "May improve testosterone levels",
      "Cardiovascular health",
      "Reduces risk of certain cancers",
    ],
    dosage: "1,000–5,000 IU per day; take with vitamin K2 (100–200 mcg MK-7) for optimal calcium regulation",
    timing: "With a fat-containing meal for best absorption",
    sideEffects: [
      "Toxicity possible at very high doses (>10,000 IU/day long term)",
      "Check blood levels (aim for 40–80 ng/mL)",
    ],
    evidence: "Extremely well-researched; deficiency very common (>40% of population)",
    tags: ["bone", "immune", "mood", "testosterone", "vitamins", "cancer prevention"],
  },
  {
    id: "omega-3",
    name: "Omega-3 Fatty Acids",
    category: "supplement",
    subcategory: "Essential Fats",
    fullName: "EPA/DHA Fish Oil",
    description:
      "Omega-3 fatty acids, particularly EPA and DHA, are essential polyunsaturated fats found mainly in fatty fish. They have wide-ranging benefits for cardiovascular, brain, and joint health.",
    benefits: [
      "Reduces triglycerides and cardiovascular risk",
      "Anti-inflammatory effects",
      "Improves brain health and cognitive function",
      "Supports joint health and reduces stiffness",
      "May improve mood and reduce depression",
      "Supports eye health",
      "May reduce muscle soreness post-exercise",
    ],
    dosage: "2–4 g of combined EPA+DHA per day; aim for high EPA for inflammation/mood",
    timing: "With meals to reduce fish burps and improve absorption",
    sideEffects: [
      "Fishy aftertaste (use enteric-coated caps)",
      "Mild blood thinning at high doses",
      "GI discomfort if low quality or rancid",
    ],
    evidence: "Very strong evidence for cardiovascular and inflammatory conditions",
    tags: ["cardiovascular", "inflammation", "brain", "joints", "mood", "EPA", "DHA"],
  },
  {
    id: "ashwagandha",
    name: "Ashwagandha",
    category: "supplement",
    subcategory: "Adaptogens & Herbs",
    fullName: "Withania somnifera (KSM-66, Sensoril)",
    description:
      "Ashwagandha is a powerful adaptogenic herb used in Ayurvedic medicine for thousands of years. It helps the body adapt to stress, improves resilience, and has wide-ranging health benefits.",
    benefits: [
      "Reduces cortisol and stress levels",
      "Improves anxiety and depression symptoms",
      "Increases testosterone (in men)",
      "Improves strength and muscle recovery",
      "Improves sleep quality",
      "Thyroid support",
      "Neuroprotective properties",
    ],
    dosage: "300–600 mg of KSM-66 or Sensoril extract daily",
    timing: "Morning (for energy/stress) or evening (for sleep); can be split",
    sideEffects: [
      "May cause drowsiness in some",
      "GI discomfort (take with food)",
      "Avoid in pregnancy",
      "May lower thyroid hormone levels (beneficial or not depending on individual)",
    ],
    evidence: "Strong clinical evidence for stress, anxiety, testosterone, and exercise performance",
    tags: ["adaptogen", "stress", "testosterone", "sleep", "anxiety", "cortisol"],
  },
  {
    id: "rhodiola",
    name: "Rhodiola Rosea",
    category: "supplement",
    subcategory: "Adaptogens & Herbs",
    description:
      "Rhodiola Rosea is an adaptogenic herb from Siberia and Scandinavia. It improves mental and physical performance under stress and is used to combat fatigue.",
    benefits: [
      "Reduces mental fatigue and exhaustion",
      "Improves exercise endurance",
      "Reduces stress and anxiety",
      "Improves mood and symptoms of depression",
      "Enhances cognitive performance",
      "May improve HRV (heart rate variability)",
    ],
    dosage: "200–600 mg per day of standardized extract (3% rosavins, 1% salidroside)",
    timing: "Morning or pre-workout; avoid in evening (stimulating)",
    sideEffects: [
      "Insomnia if taken late",
      "Dizziness (rare)",
      "Dry mouth",
      "Mild GI discomfort",
    ],
    evidence: "Moderate-strong clinical evidence for fatigue and stress",
    tags: ["adaptogen", "fatigue", "stress", "endurance", "mood", "cognitive"],
  },
  {
    id: "lions-mane",
    name: "Lion's Mane Mushroom",
    category: "supplement",
    subcategory: "Nootropics & Cognitive",
    fullName: "Hericium erinaceus",
    description:
      "Lion's Mane is a medicinal mushroom known for its ability to stimulate Nerve Growth Factor (NGF) production, supporting brain health, nerve regeneration, and cognitive function.",
    benefits: [
      "Stimulates NGF and BDNF production",
      "Improves memory and cognitive function",
      "Supports nerve regeneration",
      "May reduce symptoms of anxiety and depression",
      "Potential neuroprotective effects",
      "May support gut health",
    ],
    dosage: "500–3,000 mg per day (fruiting body extract preferred; look for beta-glucan content)",
    timing: "Morning or with meals",
    sideEffects: [
      "Generally well tolerated",
      "Possible allergic reaction in mushroom-allergic individuals",
      "Rare GI discomfort",
    ],
    evidence: "Promising evidence for NGF stimulation and mild cognitive improvement; more human trials needed",
    tags: ["nootropic", "NGF", "BDNF", "cognitive", "memory", "neuroprotection", "mushroom"],
  },
  {
    id: "nmn",
    name: "NMN",
    category: "supplement",
    subcategory: "Anti-Aging & Longevity",
    fullName: "Nicotinamide Mononucleotide",
    description:
      "NMN is a precursor to NAD+ (nicotinamide adenine dinucleotide), a coenzyme essential for cellular energy production and DNA repair. NAD+ levels decline with age.",
    benefits: [
      "Increases NAD+ levels",
      "Supports cellular energy production",
      "Activates sirtuins (longevity genes)",
      "May improve age-related metabolic decline",
      "Supports DNA repair",
      "Cognitive benefits reported",
      "May improve cardiovascular health",
    ],
    dosage: "250–1,000 mg per day (sublingual may improve bioavailability)",
    timing: "Morning with or without food",
    sideEffects: [
      "Generally well tolerated",
      "Nausea at high doses",
      "Flushing (less than niacin)",
      "Long-term human safety data still emerging",
    ],
    evidence: "Strong animal evidence; growing human clinical trial data",
    tags: ["NAD+", "longevity", "energy", "DNA repair", "sirtuins", "anti-aging"],
  },
  {
    id: "nr",
    name: "NR",
    category: "supplement",
    subcategory: "Anti-Aging & Longevity",
    fullName: "Nicotinamide Riboside (NIAGEN)",
    description:
      "NR is another NAD+ precursor that has been extensively studied for its ability to raise NAD+ levels. It is considered safe and has multiple published human trials.",
    benefits: [
      "Effectively raises NAD+ levels",
      "Supports mitochondrial function",
      "May improve muscle function in older adults",
      "Neuroprotective potential",
      "Anti-aging via sirtuin activation",
    ],
    dosage: "250–500 mg per day",
    timing: "Morning with or without food",
    sideEffects: ["Well tolerated in human trials", "Mild nausea at high doses", "Flushing (rare)"],
    evidence: "Multiple human RCTs showing NAD+ elevation; functional benefits still emerging",
    tags: ["NAD+", "longevity", "mitochondria", "anti-aging", "sirtuins"],
  },
  {
    id: "berberine",
    name: "Berberine",
    category: "supplement",
    subcategory: "Metabolic & Blood Sugar",
    description:
      "Berberine is an alkaloid found in several plants including barberry and goldenseal. It has powerful effects on blood sugar regulation and metabolic health, often compared to metformin.",
    benefits: [
      "Lowers blood sugar levels",
      "Improves insulin sensitivity",
      "Reduces LDL cholesterol and triglycerides",
      "Activates AMPK (cellular energy sensor)",
      "Antimicrobial properties",
      "May aid weight loss",
      "Gut microbiome modulation",
    ],
    dosage: "500 mg, 2–3 times per day with meals (1,000–1,500 mg total)",
    timing: "With meals to reduce GI side effects",
    sideEffects: [
      "GI discomfort, cramping, diarrhea (most common)",
      "Drug interactions (CYP3A4, CYP2D6)",
      "Not for use in pregnancy",
      "May interact with blood sugar medications",
    ],
    evidence: "Very strong clinical evidence; multiple meta-analyses support metabolic benefits",
    tags: ["blood sugar", "insulin", "metabolic", "cholesterol", "AMPK", "weight loss"],
  },
  {
    id: "metformin",
    name: "Metformin",
    category: "supplement",
    subcategory: "Anti-Aging & Longevity",
    description:
      "While primarily a prescription diabetes drug, Metformin is widely studied as a longevity and anti-aging agent. It activates AMPK, reduces glucose production, and has shown cancer-preventive properties.",
    benefits: [
      "Reduces blood glucose and insulin resistance",
      "Activates AMPK",
      "Anti-aging (TAME trial ongoing)",
      "May reduce cancer risk",
      "Cardiovascular protective effects",
      "Potential lifespan extension",
    ],
    dosage: "500–2,000 mg per day (prescription required; typically 500–850 mg twice daily)",
    timing: "With meals",
    sideEffects: [
      "GI side effects common initially (nausea, diarrhea)",
      "B12 depletion with long-term use (supplement B12)",
      "May blunt exercise adaptations (controversial)",
      "Rare lactic acidosis",
    ],
    evidence: "Extremely strong clinical evidence for T2D; TAME trial assessing anti-aging effects",
    tags: ["blood sugar", "AMPK", "longevity", "anti-aging", "cancer prevention", "prescription"],
  },
  {
    id: "rapamycin",
    name: "Rapamycin (Low-Dose)",
    category: "supplement",
    subcategory: "Anti-Aging & Longevity",
    description:
      "Rapamycin is an mTOR inhibitor originally developed as an immunosuppressant. At low doses, it has demonstrated lifespan extension in multiple animal models and is being studied for human longevity.",
    benefits: [
      "mTOR inhibition (promotes autophagy)",
      "Shown to extend lifespan in mice",
      "May improve healthspan",
      "Potential anti-cancer effects",
      "Immune rejuvenation at low doses",
    ],
    dosage: "2–6 mg once per week (low-dose 'pulsed' protocol for longevity; prescription only)",
    timing: "Once weekly",
    sideEffects: [
      "Mouth sores",
      "Delayed wound healing",
      "Increased infection risk at higher doses",
      "Lipid changes",
      "Must be used under medical supervision",
    ],
    evidence: "Strong animal data; PEARL trial and others ongoing in humans",
    tags: ["mTOR", "autophagy", "longevity", "anti-aging", "prescription", "lifespan"],
  },
  {
    id: "coq10",
    name: "CoQ10",
    category: "supplement",
    subcategory: "Cellular Energy",
    fullName: "Coenzyme Q10 (Ubiquinone / Ubiquinol)",
    description:
      "CoQ10 is a fat-soluble antioxidant found in nearly every cell of the body. It is essential for mitochondrial energy production and declines significantly with age.",
    benefits: [
      "Supports mitochondrial energy production (ATP)",
      "Powerful antioxidant",
      "Cardiovascular health (reduces blood pressure, improves heart function)",
      "May improve exercise tolerance",
      "Reduces statin-associated muscle pain (myopathy)",
      "Neuroprotective properties",
    ],
    dosage: "100–300 mg of ubiquinol (reduced form) per day; ubiquinol preferred over ubiquinone for those over 40",
    timing: "With a fat-containing meal",
    sideEffects: [
      "Generally very safe",
      "Mild GI discomfort",
      "May lower blood pressure (monitor if on medications)",
    ],
    evidence: "Strong evidence for cardiovascular benefits and statin-induced myopathy",
    tags: ["mitochondria", "energy", "cardiovascular", "antioxidant", "statins", "ATP"],
  },
  {
    id: "alpha-lipoic-acid",
    name: "Alpha Lipoic Acid",
    category: "supplement",
    subcategory: "Antioxidants",
    fullName: "ALA (R-ALA for enhanced efficacy)",
    description:
      "Alpha Lipoic Acid is a potent antioxidant that is both water and fat soluble, allowing it to work in all cell compartments. It regenerates other antioxidants and has anti-diabetic properties.",
    benefits: [
      "Powerful universal antioxidant",
      "Regenerates vitamins C and E",
      "Improves insulin sensitivity",
      "Supports nerve health in diabetic neuropathy",
      "May support weight loss",
      "Anti-aging effects via autophagy modulation",
    ],
    dosage: "R-ALA: 100–300 mg per day; racemic ALA: 300–600 mg per day",
    timing: "On an empty stomach (improves absorption)",
    sideEffects: [
      "Nausea if taken without food",
      "May lower blood sugar (monitor in diabetics)",
      "B1 (thiamine) depletion with very high doses",
    ],
    evidence: "Good evidence for diabetic neuropathy and antioxidant effects",
    tags: ["antioxidant", "insulin", "neuropathy", "anti-aging", "weight loss"],
  },
  {
    id: "resveratrol",
    name: "Resveratrol",
    category: "supplement",
    subcategory: "Anti-Aging & Longevity",
    description:
      "Resveratrol is a polyphenol found in red wine, grapes, and berries. It activates sirtuins (SIRT1) and has anti-inflammatory, cardiovascular, and anti-aging properties.",
    benefits: [
      "Sirtuin activation (SIRT1)",
      "Cardiovascular protective effects",
      "Anti-inflammatory properties",
      "May improve insulin sensitivity",
      "Antioxidant",
      "Potential neuroprotective effects",
    ],
    dosage: "100–500 mg per day (resveratrol with pterostilbene or piperine for improved bioavailability)",
    timing: "With food; often taken with NMN for synergistic effects",
    sideEffects: [
      "GI discomfort at high doses",
      "May interact with blood thinners",
      "Bioavailability issues (consider micronized or transresveratrol)",
    ],
    evidence: "Promising animal data; human trials show modest effects on metabolism and cardiovascular",
    tags: ["sirtuin", "longevity", "anti-aging", "cardiovascular", "antioxidant", "polyphenol"],
  },
  {
    id: "l-carnitine",
    name: "L-Carnitine",
    category: "supplement",
    subcategory: "Metabolic & Performance",
    description:
      "L-Carnitine is an amino acid derivative that transports fatty acids into mitochondria for energy production. It plays a key role in fat metabolism and energy generation.",
    benefits: [
      "Promotes fat burning (fat transport into mitochondria)",
      "Improves exercise performance and recovery",
      "May improve insulin sensitivity",
      "Cognitive and neuroprotective effects (Acetyl-L-Carnitine)",
      "Cardiovascular benefits",
      "Male fertility (improves sperm quality)",
    ],
    dosage: "1–4 g per day; Acetyl-L-Carnitine (ALCAR): 500–2,000 mg for cognitive benefits",
    timing: "Before exercise or with meals",
    sideEffects: [
      "Fishy body odor at high doses",
      "GI discomfort",
      "TMAO production (gut bacteria convert carnitine; consider red meat diet context)",
    ],
    evidence: "Good evidence for athletic performance and male fertility; cognitive evidence mainly from ALCAR",
    tags: ["fat burning", "performance", "mitochondria", "cognitive", "fertility", "ALCAR"],
  },
  {
    id: "glutamine",
    name: "L-Glutamine",
    category: "supplement",
    subcategory: "Protein & Amino Acids",
    description:
      "Glutamine is the most abundant amino acid in the body. It is conditionally essential during stress, illness, or intense exercise and plays key roles in immune function and gut health.",
    benefits: [
      "Supports gut lining integrity (leaky gut)",
      "Immune system support",
      "Reduces muscle soreness post-exercise",
      "Supports recovery from illness or surgery",
      "May reduce sugar cravings",
    ],
    dosage: "5–10 g per day (up to 20–30 g/day in clinical settings)",
    timing: "Post-workout or before bed; can be used throughout the day",
    sideEffects: ["Generally very safe", "Very high doses may increase ammonia levels"],
    evidence: "Strong evidence for gut health and immune support; moderate for exercise recovery",
    tags: ["gut health", "immune", "recovery", "muscle", "amino acids"],
  },
  {
    id: "taurine",
    name: "Taurine",
    category: "supplement",
    subcategory: "Metabolic & Performance",
    description:
      "Taurine is a conditionally essential amino acid found in high concentrations in the heart, brain, and muscles. It has antioxidant, cardiovascular, and metabolic benefits.",
    benefits: [
      "Cardiovascular protection",
      "Antioxidant and anti-inflammatory",
      "Improves exercise performance and reduces fatigue",
      "Supports eye health",
      "Regulates blood sugar",
      "Neuroprotective effects",
      "Recent research links taurine decline to aging",
    ],
    dosage: "500–3,000 mg per day",
    timing: "Pre-workout or anytime",
    sideEffects: ["Extremely safe at standard doses", "High doses may lower blood pressure"],
    evidence: "Strong preclinical; growing human evidence; recent landmark study on aging (2023)",
    tags: ["cardiovascular", "antioxidant", "performance", "aging", "brain", "eye health"],
  },
  {
    id: "melatonin",
    name: "Melatonin",
    category: "supplement",
    subcategory: "Sleep & Recovery",
    description:
      "Melatonin is a hormone produced by the pineal gland that regulates the sleep-wake cycle. Supplemental melatonin is used for sleep disorders, jet lag, and has emerging anti-aging properties.",
    benefits: [
      "Regulates sleep onset and circadian rhythm",
      "Reduces jet lag",
      "Powerful antioxidant",
      "Anti-inflammatory effects",
      "May have anti-cancer properties",
      "Immune modulation",
    ],
    dosage: "0.5–3 mg for sleep (lower doses more physiological); up to 10 mg used clinically",
    timing: "30–60 minutes before desired sleep time",
    sideEffects: [
      "Morning grogginess (reduce dose)",
      "May shift circadian rhythm if timed incorrectly",
      "Avoid high doses long-term without medical guidance",
    ],
    evidence: "Strong evidence for circadian disruption and jet lag; good antioxidant research",
    tags: ["sleep", "circadian", "antioxidant", "immune", "anti-aging"],
  },
  {
    id: "l-theanine",
    name: "L-Theanine",
    category: "supplement",
    subcategory: "Nootropics & Cognitive",
    description:
      "L-Theanine is an amino acid found naturally in green tea. It promotes relaxation without sedation and synergizes powerfully with caffeine to improve focus and reduce anxiety.",
    benefits: [
      "Promotes calm focus without drowsiness",
      "Reduces anxiety",
      "Synergizes with caffeine (improved focus, reduced jitteriness)",
      "Improves sleep quality",
      "May reduce blood pressure",
    ],
    dosage: "100–200 mg alone; 200 mg with 100 mg caffeine (2:1 ratio)",
    timing: "With coffee/caffeine, or before bed",
    sideEffects: ["Extremely safe", "May cause drowsiness at high doses"],
    evidence: "Strong evidence for cognitive and anxiety effects especially with caffeine",
    tags: ["cognitive", "anxiety", "focus", "sleep", "caffeine synergy"],
  },
  {
    id: "collagen",
    name: "Collagen Peptides",
    category: "supplement",
    subcategory: "Structural & Joint",
    description:
      "Hydrolyzed collagen peptides provide bioavailable amino acids (glycine, proline, hydroxyproline) that support collagen synthesis in skin, joints, tendons, and ligaments.",
    benefits: [
      "Improves skin elasticity and hydration",
      "Reduces joint pain and supports cartilage",
      "Supports tendon and ligament repair",
      "Improves bone density",
      "May support gut lining (glycine content)",
    ],
    dosage: "10–15 g per day (look for Type I/III for skin/tendons; Type II for joints)",
    timing: "With vitamin C to maximize collagen synthesis; post-workout for joint/tendon support",
    sideEffects: ["Generally very safe", "Poor quality products may have heavy metals (choose tested brands)"],
    evidence: "Good evidence for skin and joint benefits; moderate for bone health",
    tags: ["skin", "joints", "tendons", "bone", "gut health"],
  },
  {
    id: "vitamin-c",
    name: "Vitamin C",
    category: "supplement",
    subcategory: "Vitamins",
    fullName: "Ascorbic Acid / Sodium Ascorbate",
    description:
      "Vitamin C is a water-soluble vitamin and essential cofactor for collagen synthesis, immune function, and iron absorption. It is a powerful antioxidant.",
    benefits: [
      "Essential for collagen synthesis",
      "Immune support",
      "Powerful antioxidant",
      "Enhances iron absorption",
      "Reduces oxidative stress",
      "Adrenal support (high concentrations in adrenal glands)",
    ],
    dosage: "500–2,000 mg per day in divided doses (liposomal C for better absorption at high doses)",
    timing: "With meals to reduce GI upset; split into 2–3 doses",
    sideEffects: [
      "Diarrhea at high doses (bowel tolerance threshold varies)",
      "Kidney stone risk at very high doses in those with history",
    ],
    evidence: "Essential vitamin; strong evidence for immune and antioxidant function",
    tags: ["immune", "antioxidant", "collagen", "iron", "vitamins"],
  },
  {
    id: "vitamin-k2",
    name: "Vitamin K2",
    category: "supplement",
    subcategory: "Vitamins",
    fullName: "Menaquinone (MK-4, MK-7)",
    description:
      "Vitamin K2 is a fat-soluble vitamin that activates proteins responsible for directing calcium to bones and teeth, preventing arterial calcification. MK-7 has the longest half-life.",
    benefits: [
      "Directs calcium to bones (prevents arterial calcification)",
      "Cardiovascular protection",
      "Supports bone density",
      "Essential companion to Vitamin D3",
      "May reduce coronary artery calcification",
    ],
    dosage: "100–200 mcg MK-7 per day (taken with D3 and calcium)",
    timing: "With fat-containing meal",
    sideEffects: ["Generally very safe", "May interact with warfarin/blood thinners"],
    evidence: "Strong observational evidence; growing interventional trial data",
    tags: ["bone", "cardiovascular", "calcium", "vitamins", "D3 synergy"],
  },
  {
    id: "probiotics",
    name: "Probiotics",
    category: "supplement",
    subcategory: "Gut Health",
    description:
      "Probiotics are live beneficial bacteria that support gut microbiome health. A healthy microbiome influences digestion, immunity, mental health, and systemic inflammation.",
    benefits: [
      "Supports healthy gut flora",
      "Improves digestion and reduces bloating",
      "Immune system modulation",
      "May reduce anxiety and depression (gut-brain axis)",
      "Helps restore microbiome after antibiotics",
      "May improve skin conditions",
    ],
    dosage: "1–100 billion CFU per day depending on strain and condition; multi-strain generally preferred",
    timing: "Before or with meals",
    sideEffects: [
      "Initial bloating/gas as microbiome adjusts",
      "Rare overgrowth in immunocompromised individuals",
    ],
    evidence: "Strong for specific conditions (IBS, antibiotic recovery); strain-specific effects",
    tags: ["gut health", "immune", "digestion", "microbiome", "brain-gut axis"],
  },
  {
    id: "caffeine",
    name: "Caffeine",
    category: "supplement",
    subcategory: "Nootropics & Cognitive",
    description:
      "Caffeine is the world's most widely used psychoactive substance. It works by blocking adenosine receptors, increasing alertness, energy, and performance.",
    benefits: [
      "Increases alertness and focus",
      "Improves physical performance (endurance, strength, power)",
      "Enhances fat oxidation",
      "Boosts mood",
      "May reduce risk of Parkinson's and Alzheimer's",
    ],
    dosage: "100–400 mg per day; 3–6 mg/kg body weight for exercise performance",
    timing: "Pre-workout (45–60 min before); avoid within 6 hours of sleep",
    sideEffects: [
      "Anxiety at high doses",
      "Insomnia if taken too late",
      "Tolerance develops quickly",
      "Withdrawal headaches",
      "Dependency",
    ],
    evidence: "Extensive evidence; one of the most studied ergogenic aids",
    tags: ["cognitive", "performance", "fat loss", "alertness", "ergogenic"],
  },
  {
    id: "citrulline",
    name: "L-Citrulline",
    category: "supplement",
    subcategory: "Performance & Strength",
    description:
      "L-Citrulline is an amino acid that converts to arginine in the kidneys, increasing nitric oxide production. It improves blood flow, reduces fatigue, and enhances exercise performance.",
    benefits: [
      "Increases nitric oxide production",
      "Improves exercise performance and endurance",
      "Reduces muscle soreness",
      "May improve erectile function (via NO pathway)",
      "Reduces blood pressure",
    ],
    dosage: "6–8 g of L-Citrulline (or 8–10 g citrulline malate) 30–60 min pre-workout",
    timing: "Pre-workout",
    sideEffects: ["Generally very well tolerated", "Possible GI discomfort at high doses"],
    evidence: "Strong evidence for exercise performance and blood pressure reduction",
    tags: ["performance", "nitric oxide", "blood flow", "endurance", "muscle pump"],
  },
  {
    id: "beta-alanine",
    name: "Beta-Alanine",
    category: "supplement",
    subcategory: "Performance & Strength",
    description:
      "Beta-Alanine is a non-essential amino acid that combines with histidine to form carnosine in muscles. Carnosine buffers lactic acid accumulation, delaying fatigue during high-intensity exercise.",
    benefits: [
      "Increases muscle carnosine levels",
      "Delays fatigue during high-intensity exercise",
      "Improves performance in 1–4 minute efforts",
      "May increase lean mass over time",
    ],
    dosage: "3.2–6.4 g per day (split into smaller doses to reduce paresthesia)",
    timing: "Anytime; timing less critical as it builds up over weeks",
    sideEffects: [
      "Paresthesia (tingling/flushing) is common and harmless",
      "Reduce dose or use sustained-release to minimize tingling",
    ],
    evidence: "Strong meta-analytic evidence for endurance and high-intensity performance",
    tags: ["performance", "endurance", "carnosine", "fatigue", "muscle"],
  },
];

const allData = [...peptideData, ...supplementData];
